### ISSUE TITLE
Changing the accent color isn't properly applied

### ISSUE THREAD

**Issue by pixelcmtd** [Amplus2/Amplissimus#16]
**To Reproduce**
1. Change the accent color
2. Look at the Dev Options or open the App Info
3. See error

**Screenshots/Stacktraces/Logs**
<img width="712" alt="Screenshot 2021-03-27 at 17 42 43" src="https://user-images.githubusercontent.com/35269695/112728252-a7b33180-8f26-11eb-9062-34250b04b27b.png">
<img width="712" alt="Screenshot 2021-03-27 at 17 43 29" src="https://user-images.githubusercontent.com/35269695/112728273-b8fc3e00-8f26-11eb-8d5d-1855c49371bb.png">

**Versions (please complete the following information):**
 - OS version: macOS 11.2.3
 - App Version: 4.0.76

**Comment by pixelcmtd** [comment]
this was reintroduced in one of the last commits

**Comment by pixelcmtd** [comment]
i'm rn in the middle of bisecting

**Comment by pixelcmtd** [comment]
it was somewhere between 1b10322dd3f5bf3e307c911b915dc6413b3b7b95 (not present) and 30d73d0efdc814404d03224fa690095939ac189d (present), so probably @Luddifee is at fault

**Comment by chrissxYT** [comment]
not present in cf8e6a508e0bdba8cf3689679a19667585ab03ee, cant get bd6a3f1e82ebbecf9b319d6119c2703b8882fc16 to compile

**Comment by chrissxYT** [comment]
it's present in bd6a3f1e82ebbecf9b319d6119c2703b8882fc16

**Comment by chrissxYT** [comment]
it was introduced in b5ea62ed5a0561cb9826cefb16cda4cb6108fe6b

**Comment by pixelcmtd** [comment]
it was introduced in b5ea62ed5a0561cb9826cefb16cda4cb6108fe6b, but i dont get why

**Comment by chrissxYT** [comment]
oh it is obvious: `AmpTabBar` extends `Container`, which is a `StatelessWidget`, so it isn't refreshed

**Comment by pixelcmtd** [comment]
i have basically manually reverted that one and it doesnt work
