### ISSUE TITLE
TextField's Theme data not changing

### ISSUE THREAD

**Issue by lehlud** [Amplus2/Amplissimus#21]
**Describe the bug**
A TextField's Theme data not changing even if it should.

**To Reproduce**
1. Change accent color
2. Tap on input field
3. See error

**Screenshots/Stacktraces/Logs**
![Screenshot_1616928245](https://user-images.githubusercontent.com/58045323/112749594-979d5f80-8fc3-11eb-9def-5359305a45a8.png)

**Versions (please complete the following information):**
 - Android 11

**Comment by pixelcmtd** [comment]
oh i think i know what the problem is, but im not sure about the fix

**Comment by pixelcmtd** [comment]
oh no, i think i was wrong

**Comment by pixelcmtd** [comment]
this is not a new issue, but rather the fix for #16 broke

**Comment by pixelcmtd** [comment]
<img width="712" alt="Screenshot 2021-03-30 at 03 54 28" src="https://user-images.githubusercontent.com/35269695/112921789-b0189180-910b-11eb-9c72-6fadbf6a0a9f.png">

just verified that this was already fixed in f5fe954290f26095b8f59b51b985d51c126fd7f6
