### ISSUE TITLE
chrissx fucked everything up

### ISSUE THREAD

**Issue by lehlud** [Amplus2/Amplissimus#23]
**Describe the bug**
The title says it all. The "error [...] occurred" error is not a part of the problem.

**To Reproduce**
1. Open app
2. See error

**Screenshots/Stacktraces/Logs**
![Screenshot_1617114147](https://user-images.githubusercontent.com/58045323/113007062-2ce05580-9176-11eb-99bb-137ff7173304.png)

**Versions (please complete the following information):**
 - Android 11

**Comment by lehlud** [comment]
commit c0ea610 (chrissx saw a problem where there was none and caused one) created this bug and chrissx is stupid

**Comment by lehlud** [comment]
BTW I'm not a poet
but BTW I use arch

**Comment by lehlud** [comment]
fixed by ddff7e4 but kept open until chrissx sees what he should not do

**Comment by lehlud** [comment]
this is what it looks like after commit ddff7e4:
![Screenshot_1617114972](https://user-images.githubusercontent.com/58045323/113007144-3ff32580-9176-11eb-9cee-651929cf91e2.png)

So as a sidenote for @chrissxYT: ask before removing something that seems to be nonsense

**Comment by pixelcmtd** [comment]
Sidenote for @Luddifee: If you are not using SafeArea, **you** are **very** stupid.

**Comment by lehlud** [comment]
Sidenote for @chrissxYT: If you are using SafeArea in this context, you have no clue what it's made for.
