### ISSUE TITLE
Haptic feedback

### ISSUE THREAD

**Issue by pixelcmtd** [Amplus2/Amplissimus#26]
**Is your feature request related to a problem? Please describe.**
Haptic feedback is cool, because it makes you feel things.

**Describe the solution you'd like**
Make part of the `uilib` use vibration.

@Luddifee now seems to be interested, wow.
<img width="351" alt="Screenshot 2021-04-05 at 23 01 34" src="https://user-images.githubusercontent.com/35269695/113626936-0f722680-9663-11eb-947b-59b422fb6565.png">

**Comment by lehlud** [comment]
closed by af026d4 and b227510
