### ISSUE TITLE
Bad contrast again due to colors

### ISSUE THREAD

**Issue by pixelcmtd** [Amplus2/Amplissimus#38]
**Describe the bug**
Some colors have bad contrast in `ampDialog`s.

**Screenshots/Stacktraces/Logs**
![Screenshot 2021-04-25 at 17 19 59](https://user-images.githubusercontent.com/35269695/116001449-ca536b80-a5f4-11eb-8b68-e154eca5bb89.png)

**Versions (please complete the following information):**
 - OS version: macOS 11.2.3
 - App Version: any since 4.0

**Comment by lehlud** [comment]
This is the reason why purple should **not** be the default color.

**Comment by pixelcmtd** [comment]
no, it isnt. we just need to fix this. a shitty default color without bad contrast isnt really any better.
