### ISSUE TITLE
Redesign the all classes ↔ your class switch

### ISSUE THREAD

**Issue by pixelcmtd** [Amplus2/Amplissimus#6]
**Is your feature request related to a problem? Please describe.**
As mentioned in Ampless/Amplessimus#38, the current design of the switch really confuses people. I have heard this from people already for a bit before opening that issue, but it is really hard to come to a solution.

**Describe the solution you'd like**
Hire some really good UI designer to solve this.

**Describe alternatives you've considered**
Get @Luddifee to redesign it.

**Comment by lehlud** [comment]
fixed by bb722df
